version: "3.8"

services:
  service:
    build: 
      context: .
      args:
        - ARG INSTALL_REQUIREMENTS=false
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379